export const nowPlayingMoviesList = {
  dates: {
    maximum: "2025-07-16",
    minimum: "2025-06-04",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/nKyBbFSooRPTJVqjrDteD1lF733.jpg",
      genre_ids: [28, 12, 18],
      id: 1011477,
      original_language: "en",
      original_title: "Karate Kid: Legends",
      overview:
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      popularity: 612.5718,
      poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
      release_date: "2025-05-08",
      title: "Karate Kid: Legends",
      video: false,
      vote_average: 7.236,
      vote_count: 312,
    },
    {
      adult: false,
      backdrop_path: "/x58Gk2ZGU5AEBp25MQe2nhZhd5z.jpg",
      genre_ids: [28, 14],
      id: 846422,
      original_language: "en",
      original_title: "The Old Guard 2",
      overview:
        "Andy and her team of immortal warriors fight with renewed purpose as they face a powerful new foe threatening their mission to protect humanity.",
      popularity: 470.299,
      poster_path: "/wqfu3bPLJaEWJVk3QOm0rKhxf1A.jpg",
      release_date: "2025-07-01",
      title: "The Old Guard 2",
      video: false,
      vote_average: 6.12,
      vote_count: 408,
    },
    {
      adult: false,
      backdrop_path: "/sItIskd5xpiE64bBWYwZintkGf3.jpg",
      genre_ids: [28, 53, 80],
      id: 541671,
      original_language: "en",
      original_title: "Ballerina",
      overview:
        "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
      popularity: 480.9303,
      poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
      release_date: "2025-06-04",
      title: "Ballerina",
      video: false,
      vote_average: 7.437,
      vote_count: 883,
    },
    {
      adult: false,
      backdrop_path: "/xABhldZaMb6wfCH5oigV333OYnb.jpg",
      genre_ids: [28, 53, 35],
      id: 749170,
      original_language: "en",
      original_title: "Heads of State",
      overview:
        "The UK Prime Minister and US President have a public rivalry that risks their countries' alliance. But when they become targets of a powerful enemy, they're forced to rely on each other as they go on a wild, multinational run. Allied with Noel, a brilliant MI6 agent, they must find a way to thwart a conspiracy that threatens the free world.",
      popularity: 403.4917,
      poster_path: "/lVgE5oLzf7ABmzyASEVcjYyHI41.jpg",
      release_date: "2025-07-02",
      title: "Heads of State",
      video: false,
      vote_average: 6.955,
      vote_count: 364,
    },
    {
      adult: false,
      backdrop_path: "/962KXsr09uK8wrmUg9TjzmE7c4e.jpg",
      genre_ids: [28, 53, 18],
      id: 1119878,
      original_language: "en",
      original_title: "Ice Road: Vengeance",
      overview:
        "Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
      popularity: 444.7102,
      poster_path: "/2vHQBX5L4yoExTa55KmGIg2Q5s3.jpg",
      release_date: "2025-06-27",
      title: "Ice Road: Vengeance",
      video: false,
      vote_average: 6.972,
      vote_count: 90,
    },
  ],
  total_pages: 238,
  total_results: 4754,
};